// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfSHkZvZHUft2Ufr0VxFrF-4WC6kUMDZY',
    appId: '1:202317038362:web:d96b843f1ecbdd45f4a2a3',
    messagingSenderId: '202317038362',
    projectId: 'trello-tasks-sync',
    authDomain: 'trello-tasks-sync.firebaseapp.com',
    storageBucket: 'trello-tasks-sync.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBboVfXCDVzDPOhmcHSHiznrWtui8XTMmk',
    appId: '1:202317038362:android:43063a558bc9b65cf4a2a3',
    messagingSenderId: '202317038362',
    projectId: 'trello-tasks-sync',
    storageBucket: 'trello-tasks-sync.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8lVfwO7ZQJaJqS8XR61Wt_txV4cbHin0',
    appId: '1:202317038362:ios:7953406cf29015bdf4a2a3',
    messagingSenderId: '202317038362',
    projectId: 'trello-tasks-sync',
    storageBucket: 'trello-tasks-sync.appspot.com',
    iosBundleId: 'com.example.trelloTasksSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8lVfwO7ZQJaJqS8XR61Wt_txV4cbHin0',
    appId: '1:202317038362:ios:c46b5f32a14a3f34f4a2a3',
    messagingSenderId: '202317038362',
    projectId: 'trello-tasks-sync',
    storageBucket: 'trello-tasks-sync.appspot.com',
    iosBundleId: 'com.example.trelloTasksSync.RunnerTests',
  );
}
